### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by mike-leber** [andyplak/events-manager-tax-per-event#4]
Looking for a tweak like this. How does it have to be installed?

**Comment by andyplak** [comment]
This is a standalone plugin (albeit requiring Events Manager to be installed). Just install it like any other WordPress plugin. Either git clone into your plugins dir, or download the zip and copy to wp-content/plugins or upload via the plugins interface.

**Comment by andyplak** [comment]
@mike-leber I've added a readme file with install instructions. Let me know how you get on with the plugin.

**Comment by mike-leber** [comment]
Awesome! Works perfectly! thx
